[package]
name = "boucing_ball"
version = "0.1.0"
edition = "2024"

[dependencies]
glium = "0.36.0"
my_glium_util = { git = "https://github.com/CorentinVaillant/my_glium_utils.git", version = "0.1.0" }
